FROM ubuntu:16.04
MAINTAINER Masami Hiramatsu <mhiramat@kernel.org>

# archs for kretprobe
ENV ARCHS="i386 x86_64 arm arm64 ia64 mips powerpc s390 sparc64 sh openrisc"

# Install basic tools
RUN apt-get update
RUN apt-get install -y xz-utils lftp curl sudo build-essential bc gawk flex bison libssl-dev libelf-dev libisl-dev u-boot-tools
# RUN curl -L https://git.kernel.org/pub/scm/linux/kernel/git/wfg/lkp-tests.git/plain/sbin/make.cross > /usr/bin/make.cross && chmod a+x /usr/bin/make.cross
COPY make.cross /usr/bin/make.cross
RUN chmod a+x /usr/bin/make.cross

# for sh, we will use ubuntu build
RUN apt install -y gcc-sh4-linux-gnu && mkdir -p /opt/gcc-5/sh4-linux/bin/ && for bin in /usr/bin/sh4-linux-gnu-* ; do ln -s $bin /opt/gcc-5/sh4-linux/bin/sh4-linux-${bin##/usr/bin/sh4-linux-gnu-} ; done

# Install cross tools for linux
RUN mkdir /tmp/dummy && echo "all:" > /tmp/dummy/Makefile && echo "	true" >> /tmp/dummy/Makefile && cd /tmp/dummy && for arch in $ARCHS; do make.cross ARCH=$arch ; done && cd / && rm -rf /tmp/dummy

# You must bind your kernel tree under /opt/linux
RUN mkdir /opt/linux
VOLUME ["/opt/linux"]

COPY cross-build.sh /opt/
WORKDIR /opt
CMD ./cross-build.sh $ARCHS
